{% set name = "dtool_ibeis" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/dtool_ibeis/dtool_ibeis-{{ version }}.tar.gz
  sha256: 9674d6ef4a3a13f4fa0fb938e2987a105d6a42e31114922f51dc9874a31ef7ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - six
    - numpy
    - utool
    - ubelt
    - parse
    - networkx
    - cachetools

test:
  imports:
    - dtool_ibeis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Erotemic/dtool_ibeis
  summary: Data Tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
