{% set name = "dtool_ibeis" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool_ibeis/dtool_ibeis-{{ version }}.tar.gz
  sha256: fca2583ed4b71f467ae06f390f95af3067e1a8e1cdc76a8f00ff8c023247c293

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - six
    - numpy
    - utool
    - ubelt
    - parse
    - networkx

test:
  imports:
    - dtool_ibeis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Erotemic/dtool_ibeis
  summary: Data Tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
